Repository redBorder/redborder-ips, pull requests merged in 2023-11, with the labels that each got.

#10 Rhel9
  README.md
  packaging/rpm/redborder-ips.spec
Labels: kind/bug, size/XS

#11 Feature/#15799 add network scripts
  packaging/rpm/redborder-ips.spec
  resources/scripts/rb_init_conf.rb
Labels: kind/feature, size/S

#12 Add dhclient package
  packaging/rpm/redborder-ips.spec
Labels: size/XS, kind/feature

#13 release 1.3.4
  packaging/rpm/redborder-ips.spec
Labels: size/XS, kind/documentation
