Repository redBorder/redborder-ips, pull requests merged in 2024-05, with the labels that each got.

#22 Add missing rb_snort_iplist script
  resources/bin/rb_snort_iplist
Labels: bug, size/M

#25 Release 1.4.1
  .github/rpm.yml
  README.md
  VERSION
  packaging/rpm/redborder-ips.spec
  resources/bin/rb_snort_iplist
Labels: bug, kind/documentation, size/L

#23 change of kernel logging in terminal
  packaging/rpm/redborder-ips.spec
Labels: size/XS

#28 Feature/add rename network interfaces to setup wizard
  resources/bin/rb_rename_network_interfaces.sh
  resources/lib/rb_config_utils.rb
  resources/scripts/rb_setup_wizard.rb
Labels: kind/feature, size/L, feature

#29 Release 0.1.6
  VERSION
  resources/bin/rb_rename_network_interfaces.sh
  resources/lib/rb_config_utils.rb
  resources/scripts/rb_setup_wizard.rb
Labels: kind/documentation, size/L
